<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/18
 * Time: 15:28
 */

namespace backend\modules\server\controllers;

use Yii;
use backend\controllers\BaseController;


class IndexController extends BaseController
{

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        return true;
    }

    public function actionIndex(){

        return $this->display('index.html');
    }

    /**
     * 退出
     * @return \yii\web\Response
     */
    public function actionLogout(){
        Yii::$app->user->logout();
        return $this->goHome();
    }
}