<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/18
 * Time: 15:15
 */

namespace backend\modules\home\controllers;

use Yii;
use common\controllers\ComController;
use common\models\admin\User;
use common\models\admin\LoginForm;


class LoginController extends ComController
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        return true;
    }



    public function actionIndex(){

        if(!Yii::$app->user->isGuest){
            return $this->goHome();
        }

        $model = new LoginForm();
        $model->rememberMe = false;
        if($model->load(Yii::$app->request->post())){
            $res = $model->loginAdmin();
            if($res['error_code'] == 1){
                ajaxReturn(1,$res['msg']);
            }

            ajaxReturn(0,'登录成功',htmlUrl(['/server/index/index']));
        }else{
            return $this->display('login.html');
        }

    }



















}